### PR TITLE
Update theme for Ghost 4 compatibility

### PR DESCRIPTION
**Pull request by RapidCompiler**

### CODE REVIEW

**Comment by aakashhemadri** [comment]
Compiles and runs successfully! I would be happy to merge and update the theme. This looks like ghost v4. Can you pull newer liebling versions as well? So we can test together? @RapidCompiler

**Comment by aakashhemadri** [comment]
What will have I have to do on the ghost server side? Will I have to update ghost version, as far as I can see this is the latest 1.0.6 release of leibling. Can you confirm this? So I am assuming that this is Ghost v4

**Comment by aakashhemadri** [comment]
One issue I think we should look into is the footer socials, Idk why they are broken but they seem to be broken even in the current production site.

**Comment by RapidCompiler** [comment]
> What will have I have to do on the ghost server side? Will I have to update ghost version, as far as I can see this is the latest 1.0.6 release of leibling. Can you confirm this? So I am assuming that this is Ghost v4

Yes, this theme is Ghost v4 compatible. I'm not quite sure what else is required on the server side apart from bumping up the CMS version. Could we possibly test this on a different server before pushing it into production, or is there another way?


> One issue I think we should look into is the footer socials, Idk why they are broken but they seem to be broken even in the current production site.
<p align="center">
Fifth Footer Social Link
</p>
I don't understand the purpose of the final fifth link. It takes me the page shown below.

the-bridge-rss-2
If this is the behavior expected from this hyperlink, then I see no problem with the footer socials. All other links seem to be working just fine in the current production site. Is there something I'm missing?


> Compiles and runs successfully! I would be happy to merge and update the theme. This looks like ghost v4. Can you pull newer liebling versions as well? So we can test together? @RapidCompiler

Yeah sure, I'll check if there are any newer commits in the original upstream repo and include them. Probably have to create a new PR, though.

**Comment by aakashhemadri** [comment]
> Yes, this theme is Ghost v4 compatible. I'm not quite sure what else is required on the server side apart from bumping up the CMS version. Could we possibly test this on a different server before pushing it into production, or is there another way?

Yes well we can try it on our local system, just spin up a local Ghost v4 instance and upload this theme as a zip. Or simply run these scripts to setup a webserver identical to the current one [https://github.com/TheBridgePSGTech/web-server](https://github.com/TheBridgePSGTech/web-server). The latter is a little excessive, cause the theme should perform on either, with only the data missing.

> I don't understand the purpose of the final fifth link. It takes me the page shown below.
> the-bridge-rss-2 If this is the behavior expected from this hyperlink, then I see no problem with the footer socials. 

This is an RSS Feed, old tech, one I use everyday, so kept it as a feature for anyone else.

> All other links seem to be working just fine in the current production site. Is there something I'm missing?

Ah no this is on me! Please ignore. My filters detected it as malicious, hence missing for me.

> Yeah sure, I'll check if there are any newer commits in the original upstream repo and include them. Probably have to create a new PR, though.

Well not particularly necessary, just fetch from liebling's remote and see if it merges with your local branch test and then finally push to the same branch as long as you don't push before testing we are good. We'd rather not open a new PR

**Comment by RapidCompiler** [comment]
> Can you pull newer liebling versions as well? So we can test together? @RapidCompiler

I've pulled the latest liebling version 1.5.0 from the upstream and merged it here. Everything seems to be working fine. Can you confirm the same? @aakashhemadri 

If there are no issues, we should be ready for testing.

**Review by aakashhemadri — APPROVED** [review]
Great work @RapidCompiler

**Pull request merged**
